#!/usr/bin/env bash

yarn prep
yarn build

mkdir -p build/short-ext

mv build/background.js build/short-ext/
cp build/manifest.json build/short-ext/
cp -r icons build/short-ext/

cd build || exit
zip -r short-ext.zip short-ext/* -x "*.DS_Store"
